table cities
	lineageTag: 6e86e1a6-7bbf-492b-a9e7-82c36dd51c02

	column CityID
		dataType: int64
		formatString: 0
		lineageTag: bad467ea-eebf-4828-83c9-b4102b94d070
		summarizeBy: none
		sourceColumn: CityID

		annotation SummarizationSetBy = Automatic

	column CityName
		dataType: string
		lineageTag: 72728654-7e36-4c7d-97f7-070c4abc8d1f
		summarizeBy: none
		sourceColumn: CityName

		annotation SummarizationSetBy = Automatic

	column Zipcode
		dataType: int64
		formatString: 0
		lineageTag: 31f148be-f074-4001-b48b-ad6155a1208f
		summarizeBy: sum
		sourceColumn: Zipcode

		annotation SummarizationSetBy = Automatic

	column CountryID
		dataType: int64
		formatString: 0
		lineageTag: 556627da-e6e0-4d4c-8f4d-df60e87b6fdf
		summarizeBy: none
		sourceColumn: CountryID

		annotation SummarizationSetBy = Automatic

	partition cities = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\ValentinoStarace\OneDrive - ITS Tech Talent Factory\Desktop\PowerBi\Laboratorio\Lavoro-Power-BI\cities.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"CityID", Int64.Type}, {"CityName", type text}, {"Zipcode", Int64.Type}, {"CountryID", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

